version: '3'
services:
  blue:
    image: photique/backend-dev:0.1.0
    container_name: blue-dev
    restart: always
    ports:
      - "8081:8080"
    networks:
      - backend
    environment:
      - TZ=Asia/Seoul


  green:
    image: photique/backend-dev:0.1.0
    container_name: green-dev
    restart: always
    ports:
      - "8082:8080"
    networks:
      - backend
    environment:
      - TZ=Asia/Seoul

networks:
  backend:
    external: true
